### PR TITLE
Fix module syntax

### PR DESCRIPTION
**Pull request by exah**
- Fix `export default from` using es6 standard syntax (for Webpack 2, Rollup.js)
- Add `module` field to `package.json`

Usage:

```js
import {  MdForward } from 'react-icons'
```

Related to #98 #78 #72, except doesn't have `main` field, and doesn't have ES5 version

### CODE REVIEW

**Comment by antoinerousseau** [comment]
@exah can you confirm that this would be a breaking change and that it's still a valid PR?

**Comment by tgriesser** [comment]
@antoinerousseau Not my PR, but I believe this should still be a valid PR, and I don't think it would be considered a breaking change, though I guess it couldn't hurt to bump the major to be safe.

```
export Name from './module'
```
is invalid module syntax
```
export { default as Name } from './module'
```
is the correct form, which this PR fixes. I'm not sure about the change to add the `module` field to package.json, since a precompiler needs to exist for the React regardless.

**Comment by antoinerousseau** [comment]
OK I'll perform some tests and merge this asap :)

**Comment by antoinerousseau** [comment]
Tested OK with `create-react-app` too using `lib/`:
```js
import Beer from 'react-icons/lib/fa/beer';
import * as FontAwesome from 'react-icons/lib/fa';
import {FaBeer} from 'react-icons/lib/fa';
```

**Pull request merged**
