### PR TITLE
Update Instagram Icon

### PR DESCRIPTION
**Pull request by emilbruckner**
Could someone update all fa icons?

### CODE REVIEW

**Comment by benhollander** [comment]
@gorangajic / @emilbruckner I can potentially help out with this.
Is there a preferred method for generating the svg files? I want to make sure any that I create are consistent with what was there before as much as possible.

**Comment by emilbruckner** [comment]
That would be great!
@benhollander What exactly do you mean by staying consistent? Shouldn't all icons be updated to their newest versions?

Thanks in advance

**Comment by benhollander** [comment]
I mean consistency in the svg files/objects. I've tried generating svgs from the fontawesome font files, with slightly different results depending on how they're generated and which library was used.

**Comment by emilbruckner** [comment]
I don't really know a lot about that …
Not involved into this repo too much

**Comment by bentatum** [comment]
I don't know if we have a programmatic way of updating libs, do we? @gorangajic

**Comment by gorangajic** [comment]
Currently no, but if someone wants to tackle that I can guide and help him. I was planning to create that but didn't have time

**Comment by bentatum** [comment]
@benhollander interested in helping us write the scripts to update libs?

**Comment by benhollander** [comment]
There are a few options.
The easiest might be to use [font-blast](https://www.npmjs.com/package/font-blast) or something like it. I'll see if I can find some time in the next couple of weeks or so.

**Pull request merged**
